apiVersion: v1
kind: PersistentVolume
metadata:
  name: mylogvol
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: vol-0e6de74e9d5dcc908
    fsType: ext4
